### PR TITLE
fix: enforce Windows filename length limit check only on Win32 platform

### LINKED ISSUE #1167: Error exceeds the maximum path length in Windows (on MAC)
### Checklist

- [x] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [x] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

Image

But I'm on MAC.

The conversion happens, but the image disappears from the preview.

### To Reproduce

Create many nested folders and inside make an upscale file.

### Upscayl Version (or commit hash)

2.15.0

### Platform

Mac DMG / Homebrew

### OS Version

Ventura 13.6

### GPU Name

Intel i9

### Expected Behavior

_No response_

### Screenshots

_No response_

### Logs

```sh
💻 System Info: {"platform":"mac","release":"22.6.0","arch":"x64","model":"Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz","cpuCount":16,"gpu":{"active":true,"cudaComputeCapabilityMajor":0,"deviceId":29504,"driverVendor":"ATI","driverVersion":"4.14.1","gpuPreference":3,"vendorId":4098}}
```

### PR DESCRIPTION
**Pull request by medinapdr**
This PR addresses an issue where the filename length check (`outFile.length >= 255`) was enforced globally, causing unnecessary errors on non-Windows systems.  

**Changes:**  
- Added a platform-specific check using `getPlatform() === "win"'` to ensure the filename length validation **only applies to Windows**.  
  - Windows has a [MAX_PATH limit of 255 characters](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation), while other OSes (Linux/macOS) support longer filenames.  

**Impact:**  
- Prevents false-positive errors on Linux/macOS when filenames exceed 255 characters.  
- Maintains compatibility with Windows file system constraints.  

**Resolves:** #1167

## Summary by CodeRabbit

- **New Features**
  - Introduced a new warning message structure across multiple languages, enhancing localization support.
  - Added a toast notification for UPSCAYL warnings in the Home component, providing users with relevant feedback during operations.

- **Bug Fixes**
  - Refined filename length validation so that warnings for excessively long names are now only shown on Windows, reducing unnecessary error messages on other operating systems.

### CODE REVIEW

**Comment by aaronliu0130** [comment]
Thanks for contributing! As mentioned in the previous PR, could you make it so the warning isn’t completely gone but no longer aborts execution? Thanks!

**Comment by medinapdr** [comment]
> Thanks for contributing! As mentioned in the previous PR, could you make it so the warning isn’t completely gone but no longer aborts execution? Thanks!

The execution is being aborted, likely due to the new version of Electron mentioned in issue #1108. I tested it with the latest release, [2.15.0](https://github.com/upscayl/upscayl/releases/tag/v2.15.0), and the problem does not occur. However, you can test the behavior by selecting the image via the 'Select Image' button.

File: electron/commands/image-upscayl.ts [hunk 1]
```diff
@@ -58,13 +59,20 @@ const imageUpscayl = async (event, payload: ImageUpscaylPayload) => {
...
+    if (getPlatform() === "win") {
+      logit("Filename too long for Windows.");
+      mainWindow.webContents.send(
+        ELECTRON_COMMANDS.UPSCAYL_ERROR,
+        "The filename exceeds the maximum path length allowed by Windows. Please shorten the filename or choose a different save location.",
+      );
+    } else {
+      mainWindow.webContents.send(
+        ELECTRON_COMMANDS.UPSCAYL_WARNING,
+        "Filename exceeds 255 characters. Your OS supports it, but might cause compatibility issues. Proceeding with upscaling.",
```
Comment (aaronliu0130) [inline electron/commands/image-upscayl.ts:73]:
```suggestion
        "The output filename exceeds 255 characters, which is over the max path length allowed by Windows, though your OS supports it. Please consider shortening the filename next time.",
```
